---
- name: prepare hosts
  hosts: all
  remote_user: ubuntu
  pre_tasks:
    - name: install some packages
      apt:
        update_cache: true
        name:
          - apt-transport-https
          - docker.io
          - python3-docker
      become: true
  roles:
    - name: setup vault cluster
      role: hashicorp-vault-cluster-role
      vars:
        vault_unsealer_inv_group_name: unsealer
        vault_cluster_inv_group_name: cluster
        vault_unsealer_port: 8202
